### ISSUE TITLE
Mapping different data type for specific field

### ISSUE THREAD

**Issue by mochadwi** [Pozo/mapstruct-kotlin#25]
TL;DR:

### Mapper
```
@Mapper
interface JobPostingMapper {
    @Mappings
    fun map(response: QuestionsResponse): Questions

    @Mappings
    fun map(model: Questions): QuestionsResponse
}
```

### Domain
```
data class Questions(
    val questionSchema: QuestionSchema,
    val questionUiSchema: Map<String, Any>,
    val answer: Map<String, Any>
)
```
### Data (DTO)
```
@Serializable
data class QuestionsResponse(
    @SerialName("question_schema")
    val questionSchema: QuestionSchema,
    @SerialName("question_ui_schema")
    val questionUiSchema: Map<String, JsonElement>,
    val answer: Map<String, JsonElement>
)
```

Does it possible to map different data type? as shown above `JsonElement` in DTO, `Any` in DOMAIN.

Because when trying the above case, error log thrown instead

### Error Log
```
JobPostingMapper.java:11: error: Internal error in the mapping processor: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0  	at java.util.ArrayList.rangeCheck(ArrayList.java:659)  	at java.util.ArrayList.get(ArrayList.java:435)  	at org.mapstruct.ap.internal.model.common.Type$TypeVarMatcher.visitDeclared(Type.java:1165)  	at org.mapstruct.ap.internal.model.common.Type$TypeVarMatcher.visitDeclared(Type.java:1141)  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:944)  	at javax.lang.model.util.AbstractTypeVisitor6.visit(AbstractTypeVisitor6.java:92)  	at org.mapstruct.ap.internal.model.common.Type.resolveTypeVarToType(Type.java:1136)  	at org.mapstruct.ap.internal.model.source.builtin.BuiltInMethod.matches(BuiltInMethod.java:70)  	at org.mapstruct.ap.internal.model.source.selector.TypeSelector.lambda$getMatchingParameterBinding$0(TypeSelector.java:158)  	at java.util.ArrayList.removeIf(ArrayList.java:1415)  	at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingParameterBinding(TypeSelector.java:157)  	at org.mapstruct.ap.internal.model.source.selector.TypeSelector.getMatchingMethods(TypeSelector.java:71)  	at org.mapstruct.ap.internal.model.source.selector.MethodSelectors.getMatchingMethods(MethodSelectors.java:62)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getBestMatch(MappingResolverImpl.java:452)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:263)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:158)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:139)  	at org.mapstruct.ap.internal.model.MapMappingMethod$Builder.build(MapMappingMethod.java:137)  	at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forgeMapMapping(PropertyMapping.java:636)  	at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.forge(PropertyMapping.java:295)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.getTargetAssignment(MappingResolverImpl.java:305)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl$ResolvingAttempt.access$100(MappingResolverImpl.java:158)  	at org.mapstruct.ap.internal.processor.creation.MappingResolverImpl.getTargetAssignment(MappingResolverImpl.java:139)  	at org.mapstruct.ap.internal.model.PropertyMapping$PropertyMappingBuilder.build(PropertyMapping.java:243)  	at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1211)  	at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.applyPropertyNameBasedMapping(BeanMappingMethod.java:1175)  	at org.mapstruct.ap.internal.model.BeanMappingMethod$Builder.build(BeanMappingMethod.java:259)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMappingMethods(MapperCreationProcessor.java:375)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.getMapper(MapperCreationProcessor.java:152)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:123)  	at org.mapstruct.ap.internal.processor.MapperCreationProcessor.process(MapperCreationProcessor.java:74)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:338)  	at org.mapstruct.ap.MappingProcessor.processMapperTypeElement(MappingProcessor.java:318)  	at org.mapstruct.ap.MappingProcessor.processMapperElements(MappingProcessor.java:267)  	at org.mapstruct.ap.MappingProcessor.process(MappingProcessor.java:166)  	at org.jetbrains.kotlin.kapt3.base.incremental.IncrementalProcessor.process(incrementalProcessors.kt)  	at org.jetbrains.kotlin.kapt3.base.ProcessorWrapper.process(annotationProcessing.kt:147)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1068)  	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing(annotationProcessing.kt:79)  	at org.jetbrains.kotlin.kapt3.base.AnnotationProcessingKt.doAnnotationProcessing$default(annotationProcessing.kt:35)  	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:45)  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  	at java.lang.reflect.Method.invoke(Method.java:498)  	at org.jetbrains.kotlin.gradle.internal.KaptExecution.run(KaptWithoutKotlincTask.kt:158)  	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:57)  	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:67)  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)  	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:63)  	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)  	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)  	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)  	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)  	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)  	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)  	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:60)  	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)  	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)  	at java.lang.Thread.run(Thread.java:748)  
public abstract interface JobPostingMapper {
```

**Comment by mochadwi** [comment]
It's supported but needs additional configurations, see TL;DR here: https://mapstruct.org/documentation/dev/reference/html/#datatype-conversions

We're ended up to use data class instead of `Any` or generic `JsonElement` to reduce boilerplate and advanced configuration in the mapper side
